In [18]:
import pandas as pd 
import numpy as np
import sklearn
# from sklearn.metrics import *
from scipy import sparse 

In [2]:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']

ratings_base = pd.read_csv('ml-100k/ub.base', sep='\t', names=r_cols, encoding='latin-1')
ratings_test = pd.read_csv('ml-100k/ub.test', sep='\t', names=r_cols, encoding='latin-1')

rate_train = ratings_base.values
rate_test = ratings_test.values

In [3]:
rate_train

array([[        1,         1,         5, 874965758],
       [        1,         2,         3, 876893171],
       [        1,         3,         4, 878542960],
       ...,
       [      943,      1188,         3, 888640250],
       [      943,      1228,         3, 888640275],
       [      943,      1330,         3, 888692465]])

In [2]:
df = pd.read_csv(open("../foody-hcm-rating-restaurant.csv",'r'))

In [3]:
df

Unnamed: 0                                               name  \
0              0                  McDonald's - Sân Bay Tân Sơn Nhất   
1              1   San Fu Lou - Ẩm Thực Quảng Đông - Phan Xích Long   
2              2                        Phố Ngon 37 - Saigon Centre   
3              3  Mộc Vị Quán - Mì Quảng & Cơm Dĩa Nóng - Sư Vạn...   
4              4                                Lotteria - Vạn Kiếp   
...          ...                                                ...   
1030        1030                 The Pizza Company - Hoàng Hoa Thám   
1031        1031  Yeebo Di Bửu - Seafood, Hot Pot & Dimsum - Lê ...   
1032        1032                         Món Huế - 209 Đinh Bộ Lĩnh   
1033        1033                         Dzị - Nhà Hàng Chay & Cafe   
1034        1034  Jangwon Korean BBQ - Buffet Nướng Bàn Đá & Lẩu...   

                                                    url  Avg_Rate  Location  \
0          /ho-chi-minh/mcdonald-s-san-bay-tan-son-nhat     7.520       7.8   
1     /ho-chi-minh/san-fu-lou-cantonese-kitchen-phan...     7.444       7.9   
2                /ho-chi-minh/pho-ngon-37-saigon-centre     7.658       8.1   
3     /ho-chi-minh/moc-vi-quan-mi-quang-com-dia-nong...     6.956       7.2   
4                        /ho-chi-minh/lotteria-van-kiep     6.686       7.3   
...                                                 ...       ...       ...   
1030      /ho-chi-minh/the-pizza-company-hoang-hoa-tham     7.728       8.1   
1031                    /ho-chi-minh/yeebo-le-thanh-ton     7.302       7.7   
1032         /ho-chi-minh/nha-hang-mon-hue-dinh-bo-linh     6.336       7.0   
1033                /ho-chi-minh/dzi-nha-hang-chay-cafe     6.430       7.1   
1034  /ho-chi-minh/jangwon-korean-bbq-buffet-nuong-b...     7.198       6.9   

      Price  Quality  Service  Space  
0       7.5      7.6      7.1    7.6  
1       6.5      7.5      7.4    7.9  
2       7.2      7.4      7.3    8.3  
3       6.9      6.9      6.8    6.9  
4       6.6      6.2      6.5    6.9  
...     ...      ...      ...    ...  
1030    7.4      8.0      7.3    7.9  
1031    6.2      7.7      7.2    7.8  
1032    6.1      6.1      5.6    7.0  
1033    6.1      6.4      5.9    6.6  
1034    7.3      7.2      7.7    6.9  

[1035 rows x 9 columns]

In [11]:
# go = df.values[:5,-5:]
go = df.values[:,-5:]
go

array([[7.8, 7.5, 7.6, 7.1, 7.6],
       [7.9, 6.5, 7.5, 7.4, 7.9],
       [8.1, 7.2, 7.4, 7.3, 8.3],
       ...,
       [7.0, 6.1, 6.1, 5.6, 7.0],
       [7.1, 6.1, 6.4, 5.9, 6.6],
       [6.9, 7.3, 7.2, 7.7, 6.9]], dtype=object)

In [12]:
gogo = np.array([[5,8,8,6,6],
       [1,1,1,1,1,],
        [8, 7.2, 7.5, 7.5, 8.3],])
gogo

array([[5. , 8. , 8. , 6. , 6. ],
       [1. , 1. , 1. , 1. , 1. ],
       [8. , 7.2, 7.5, 7.5, 8.3]])

In [13]:
vec = np.array([[10,10,10,10,10]]*len(gogo))
vec

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [19]:
sim = sklearn.metrics.pairwise.paired_distances(vec,gogo)
# sim =[]
# for i in range(len(go)):
#     sim.append(paired_distances(go[i],vec)) 
sim

array([ 8.06225775, 20.1246118 ,  5.21823725])

In [8]:
result = np.where(sim == np.amin(sim))
result[0]

array([   0,    0,    0, ..., 1034, 1034, 1034])

normalize

In [10]:
sim[64]

array([5.56956013, 5.83780781, 5.32822672, ..., 8.23286099, 8.05915628,
       6.2960305 ])

In [141]:
df.values[result]

array([[64, 'Gogi House - Nướng Hàn Quốc - An Dương Vương',
        '/ho-chi-minh/gogi-house-nuong-han-quoc-an-duong-vuong', 10.0,
        10.0, 10.0, 10.0, 10.0, 10.0],
       [129, 'Kichi Kichi Lẩu Băng Chuyền - ST Center',
        '/ho-chi-minh/kichi-kichi-lau-bang-chuyen-binh-chieu', 10.0,
        10.0, 10.0, 10.0, 10.0, 10.0],
       [345, 'Nhà Hàng Chay Giác Ngộ',
        '/ho-chi-minh/nha-hang-chay-giac-ngo', 10.0, 10.0, 10.0, 10.0,
        10.0, 10.0],
       [459, 'Pizza Hut - Nguyễn Duy Trinh',
        '/ho-chi-minh/pizza-hut-nguyen-duy-trinh', 10.0, 10.0, 10.0,
        10.0, 10.0, 10.0],
       [621, 'Meiwei - Dimsum & Hải Sản Hấp - Aeon Mall Bình Tân',
        '/ho-chi-minh/meiwei-dimsum-hai-san-hap-aeon-mall-binh-tan',
        10.0, 10.0, 10.0, 10.0, 10.0, 10.0],
       [696, 'Nhà Hàng MAIA Lounge', '/ho-chi-minh/nha-hang-maia-lounge',
        10.0, 10.0, 10.0, 10.0, 10.0, 10.0],
       [910, 'Manwah Taiwanese Hotpot - Lotte Mart Gò Vấp',
        '/ho-chi-minh/manwah-taiwa

In [59]:
df.shape()[0]

TypeError: 'tuple' object is not callable

In [25]:
gogogo = pd.read_csv(open('/home/yntn/Documents/Thesis/ML-10k-RS/travelmap-crawl-data/data/restaurant-foody-user-reviews.csv','r'))

In [60]:
gogogo

User_Id  Place_Id                                            Comment  \
0       16998881      4190  Cả nhà mình ai cũng thích ăn lẩu. Hôm lãnh lươ...   
1         941862      4190  Mình là fan của kichi đã lâu. Hôm trước vô tìn...   
2         923162    135063  Em chỉ có góp ý nhỏ về món ăn của mình. Em với...   
3         923162    886166  Không gian thoải mái mát mẻ và được trang trí ...   
4       13744194    739438  _ QUÁN VU KHỐNG NHÂN VIÊN LẤY TIỀN CỦA QUÁN, N...   
5       13744194    754942  Cuối tháng VIÊM MÀNG TÚI thì làm sao? 😢\n\n[O ...   
6       13744194    944095  Xôi ngon và lạ miệng. Các topping mix với nhau...   
7       13744194    894902                                          Đã thèm 🤤   
8       13744194    787727  Sáng nay tình cờ mình tìm thấy quán này trên N...   
9       13744194    750425  Hơi thất vọng vì không ngon như chi nhánh 3/2....   
10      13744194    133008  _ Món ăn bình thường, không ngon không dở. Bán...   
11      13744194    672962  _ Không đúng hủ tiếu Sa Đéc, vì hủ tiếu Sa Đéc...   
12      13744194     86397  Lên lịch đi ăn chổ này lâu rồi, mà đến giờ mới...   
13      13744194    935204  Cũng kha khá lâu rồi mới ăn lại cơm ở đây.\n V...   
14      13744194    964585  Thấy quán dạo gần đây khá nổi, vì mới và giá c...   
15      13744194    683284  Ăn ở đây mấy lần rồi ạ, nhưng nếu cốt dừa ngọt...   
16      13744194    664874  Sau lần đầu tiên ăn ở đây, mình đã quay lại rấ...   
17      13744194    894902  Quán tính sao với mình đây? 🙂\nLàm mình phải ă...   
18      13744194    690020  Em thèm quá, em ghiền quá, nhung mà ghé mấy lầ...   
19      13744194      1630  Thấy rất nhiều người review khen cơm tấm Ba Gh...   
20      13744194    929988  Cơm Tấm ANH CHIẾN 🍳\n\n🤸 Tụi mình là biệt đội ...   
21      13744194    664874  Lẩn đầu tiên ăn dĩa cơm no thở hổng nổi luôn đ...   
22      13744194    737790  🌸 Xôi chiên ĐH Văn Lang 🌼\n\nChú bán xôi chiên...   
23      13744194    199622  Vào Emart tránh nóng thì ăn gì?? 🍕🍕\n\nKhông c...   
24      13744194    235794  Đi vào buổi trưa nên quán cũng khá đông. Không...   
25      13744194    101668  Một chiều mưa nổi hứng thèm xôi. Chạy từ Tân B...   
26      13744194    165539  Trà nho vải 100% đường, mà nhân viên nhầm thàn...   
27      13744194    893800  Trước hay uống trà lựu đỏ nhưng mà hôm nay khô...   
28      13744194    755744  Mình thấy càng ngày càng ngon, càng đậm đà hay...   
29      13744194    760735  Ăn nhiều chổ nổi tiếng ở SG rồi, ở đây là mình...   
...          ...       ...                                                ...   
161093    202513     68613  Quán nhỏ mang phong cách hoài cổ. Rất tĩnh lặn...   
161094    202513     42028  Lần đầu ghé, Starbucks ở đây thiệt dễ thương.\...   
161095    202513     91887  Mặc dù là quán vỉa hè, nằm góc đường Phan Xích...   
161096    202513     79044  Thèm món Bún Nước Lèo nên tìm trên Foody, mới ...   
161097    202513      1348  Lâu mới ghé lại ăn. Quán có bán thêm vài món m...   
161098    202513     13439  Bên ngoài nhìn sập xệ do đường đang làm. Vừa b...   
161099    202513    137167  Đây là lần thứ 2 ghé quán, ngay buổi trưa nắng...   
161100    202513    137167  Quán nằm góc đường Hồng Hà-Bạch Đằng.\nQuán kh...   
161101    202513    240910  Cô này bán bắp là làm thêm thôi, ngày cô làm c...   
161102    202513    175672  Mình biết quán từ khi con bé, lúc nhà mình còn...   
161103    202513      2458  Mình đã ăn kem ở đây từ lúc 2k/ly kem. \nĐặc b...   
161104    202513    230846                                                NaN   
161105    202513    219254                                                NaN   
161106    202513    208920                                                NaN   
161107    202513    207380                                                NaN   
161108    202513    178761                                                NaN   
161109    202513    178121                                                NaN   
161110    202513    171070              

In [41]:
gg = pd.read_json(open('/home/yntn/Documents/Thesis/ML-10k-RS/travelmap-crawl-data/data/foody-hcm-restaurant.json','r'))
gg

Address  AvgRating  \
0     197 Nguyễn Văn Trỗi, P. 10, Quận Phú Nhuận, TP...      7.186   
1             5 Bàu Bàng, P. 13, Quận Tân Bình, TP. HCM      7.630   
2     Ga Quốc Nội Sân Bay Tân Sơn Nhất, Trường Sơn, ...      7.520   
3     195 - 197 Phan Xích Long, P. 2, Quận Phú Nhuận...      7.444   
4     L5 - 08D, Tầng 5, Saigon Centre, 65 Lê Lợi, P....      7.658   
5              732 Sư Vạn Hạnh, P. 12, Quận 10, TP. HCM      6.956   
6                   67 Vạn Kiếp, P. 13, Quận 5, TP. HCM      6.686   
7     Lầu 4, Pearl Plaza, 561A Điện Biên Phủ, P. 25,...      7.400   
8          823 Phan Văn Trị, P. 7, Quận Gò Vấp, TP. HCM      6.728   
9     284C Nguyễn Trọng Tuyển, P. 10, Quận Phú Nhuận...      7.100   
10                    151 Hai Bà Trưng, Quận 3, TP. HCM      8.240   
11    Tầng 2 Bitexco Tower, 2 Hải Triều, P. Bến Nghé...      8.748   
12                123 - 125 Nguyễn Huệ, Quận 1, TP. HCM      7.272   
13    21-23-25-27 Tôn Thất Thiệp, P. Bến Nghé, Quận ...      8.282   
14    15 Nguyễn Văn Tráng, P. Bến Thành, Quận 1, TP....      7.360   
15        521 Nguyễn Tri Phương, P. 8, Quận 10, TP. HCM      6.636   
16             68 Châu Văn Liêm, P. 11, Quận 5, TP. HCM      7.366   
17    327 - 329 Phạm Văn Đồng, P. 1, Quận Gò Vấp, TP...      5.094   
18    Vincom Center, 72 Lê Thánh Tôn, P. Bến Nghé, Q...      7.248   
19    Tầng Trệt TTTM RomeA, 117 Nguyễn Đình Chiểu, P...      8.350   
20        636 - 636A Nguyễn Trãi, P. 8, Quận 5, TP. HCM      7.614   
21    27-1 Khu Sky Garden 1, Phạm Văn Nghị, P. Tân P...      7.602   
22    147 - 149 Đường Số 7, P. Bình Trị Đông B, Quận...      4.400   
23         45 Lê Văn Việt, P. Hiệp Phú, Quận 9, TP. HCM      9.400   
24                   3A Trần Phú, P. 4, Quận 5, TP. HCM      8.000   
25    Tầng 3 AEON Mall Tân Phú, 30 Bờ Bao Tân Thắng,...      6.934   
26    Lô 02 - 37, SC VivoCity, 1058 Nguyễn Văn Linh,...      8.120   
27               179 Cao Thắng, P. 12, Quận 10, TP. HCM      7.000   
28         549 Phan Văn Trị, P. 5, Quận Gò Vấp, TP. HCM      8.500   
29                758-760 Sư Vạn Hạnh, Quận 10, TP. HCM      6.614   
...                                                 ...        ...   
1020  Tầng 3, Aeon Mall Bình Tân, 1 Đường Số 17A, P....      7.008   
1021     Grand View C, Nguyễn Đức Cảnh, Quận 7, TP. HCM      8.254   
1022  455 Lũy Bán Bích, P. Hòa Thạnh, Quận Tân Ph...      6.460   
1023       624 Nguyễn Chí Thanh, P. 4, Quận 11, TP. HCM      6.210   
1024  1 Diệp Minh Châu, P. Tân Sơn Nhì, Quận Tân Phú...      7.482   
1025        103 Đồng Khởi, P. Bến Nghé, Quận 1, TP. HCM      7.560   
1026                      36 Thảo Điền, Quận 2, TP. HCM      6.692   
1027  D2 Tầng 4 Pico Plaza, 20 Cộng Hòa, Quận Tân Bì...      5.760   
1028                      24 Thảo Điền, Quận 2, TP. HCM      7.164   
1029          25 - 25A Phạm Viết Chánh, Quận 1, TP. HCM      7.028   
1030              52 Trương Định, P. 7, Quận 3, TP. HCM      7.192   
1031  18Bis/28 Nguyễn Thị Minh Khai, P. Đa Kao, Quận...      7.396   
1032  B3-28AB, Tầng 3, Vincom Center, 72 Lê Thánh Tô...      6.670   
1033   Khách sạn Liberty Central Saigon Centre, 179 ...      7.438   
1034  L02-03, Vincom Landmark 81, 772 Điện Biên Phủ,...      8.354   
1035    290/27 Nam Kỳ Khởi Nghĩa, P. 8, Quận 3, TP. HCM      6.738   
1036  Park 1, Vinhomes Central Park, 208 Nguyễn Hữu ...      6.480   
1037  129 Nguyễn Gia Trí (Đường D2), P. 25, Quận Bìn...      5.990   
1038       80 Vũ Tông Phan, P. An Phú , Quận 2, TP. HCM      8.700   
1039            189B Nguyễn Đình Chiểu, Quận 3, TP. HCM      4.734   
1040      11 Nguyễn Bính, P. Tân Phong, Quận 7, TP. HCM      8.858   
1041  225 Thích Quảng Đức, P. 4, Quận Phú Nhuận, TP....      5.388   
1042   Tầng 1, 975 Trần Hưng Đạo, P. 5, Quận 5, TP. HCM      9.084   
1043     73 Hoàng Văn Thái, P. Tân Phú, Quận 7, TP. HCM      7.360   
1044  10D Hoàng Hoa Thám, P. 7, Quận Bình Thạnh, TP....      7.728   
1045                    1 Lê Thánh Tôn, Quận 1, TP. HCM   

In [44]:
gg[['Id','AvgRating']]

Id  AvgRating
0       4190      7.186
1     135063      7.630
2     297026      7.520
3     179996      7.444
4     248104      7.658
5     697004      6.956
6      35757      6.686
7     689061      7.400
8     784949      6.728
9     663823      7.100
10    707162      8.240
11    908452      8.748
12    196972      7.272
13    704305      8.282
14      3007      7.360
15    676906      6.636
16       151      7.366
17    207455      5.094
18    133195      7.248
19    745434      8.350
20    147170      7.614
21    300495      7.602
22    689733      4.400
23    731950      9.400
24    700663      8.000
25    225168      6.934
26    133152      8.120
27    295905      7.000
28    769154      8.500
29    763203      6.614
...      ...        ...
1020  251665      7.008
1021  676887      8.254
1022  297077      6.460
1023   85545      6.210
1024  168893      7.482
1025  641102      7.560
1026     993      6.692
1027   42697      5.760
1028  128003      7.164
1029  110997      7.028
1030    1583      7.192
1031     435      7.396
1032  118899      6.670
1033   30543      7.438
1034  764004      8.354
1035  278822      6.738
1036  707006      6.480
1037   35604      5.990
1038  200902      8.700
1039    3416      4.734
1040  790625      8.858
1041  168446      5.388
1042  886563      9.084
1043    4354      7.360
1044  785384      7.728
1045     551      7.302
1046   72011      6.336
1047  776030      7.656
1048     810      7.326
1049  690673      6.430

[1050 rows x 2 columns]